window.MEMBERS = [
	{
		name: "Abbie",
		photo: "photos/Abbie.jpg",
		role: "Interim Chair",
		joined: "February 2024",
		work: "I help run the club's social media, content creation, branding, and day-to-day operations.",
		message:
			"My dog is named Sausage Bun because I lured him home with a sausage bun.",
	},
	{
		name: "JJ",
		photo: "photos/jj.PNG",
		role: "Assistant Coach / Video Editor",
		joined: "October 2023",
		work: "Occasionally help with coaching and video editing.",
		message: "I'm the person who screams the most on the pitch.",
	},
	{
		name: "Angelina",
		photo: "photos/angelina.jpg",
		role: "Welfare Officer",
		joined: "October 2023",
		work: "Spreading love and care around the club.",
		message: "My shirt name is Geli, but not because I like clams.",
	},
	{
		name: "Jenny",
		photo: "photos/duck.jpeg",
		role: "Welfare Officer",
		joined: "November 2023",
		work: "Networking with everyone and helping with design work.",
		message: "My ideal type is Hello Kitty.",
	},
	{
		name: "Jennie",
		photo: "photos/jennie.PNG",
		role: "Marketing Team Lead",
		joined: "December 2025",
		work: "Photography, video editing, and daily social media posting.",
		message: "miaomiaomiaomiaomiaomiao",
	},
	{
		name: "Mona",
		photo: "photos/mona.jpg",
		role: "Recreational Team Manager",
		joined: "December 2023",
		work: "Supporting recreational training sessions.",
		message: "Playing football keeps women from decaying.",
	},
	{
		name: "Tina",
		photo: "photos/tina.JPG",
		role: "Recreational Team Manager",
		joined: "March 2024",
		work: "Supporting recreational training sessions.",
		message: "Everybody please play football!",
	},
	{
		name: "Yuchan",
		photo: "photos/yuchan.jpg",
		role: "Secretary",
		joined: "October 2023",
		work: "Provide administrative support, coordinate internal and external communication, and organise club activities and schedules.",
		message: "Enjoy the purest football.",
	},
	{
		name: "JZ",
		photo: "photos/jz.jpg",
		role: "Rec Manager / Captain",
		joined: "April 2026",
		work: "Support the recreational team, organise rec leagues, and assist with Saturday training sessions.",
		message: "I'm Spanish Chinese, so Spanish is actually my first language.",
	},
	{
		name: "Lele",
		photo: "photos/Lele.jpg",
		role: "Assistant Treasurer",
		joined: "July 2025",
		work: "Finance management and funding applications.",
		message: "The biggest success is walking off the pitch in one piece.",
	},
	{
		name: "Jiayi",
		photo: "photos/jiayi.jpg",
		role: "Social Secretary",
		joined: "May 2024",
		work: "Organising social events and finding ways to get everyone out together for fun.",
		message: "🔥🔥📢 JOIN US TODAY. MAKE SOCIALS GREAT AGAIN! 🎉💥🔥🔥",
	},
	{
		name: "Yihan",
		photo: "photos/yihan.jpg",
		role: "Treasurer / Dev Manager",
		joined: "October 2023",
		work: "Budget management, organising dev team leagues and training sessions, finding coaches, and keeping the atmosphere lively.",
		message:
			"When are we finally going to win the league? I want to score goals!",
	},
];
