window.MEMBERS = [
	{
		name: "Abbie",
		photo: "photos/Abbie.jpg",
		role: "临时主席",
		joined: "2024年2月",
		work: "创意内容与运营执行",
		message: "只看女足",
	},
	{
		name: "JJ",
		photo: "photos/jj.PNG",
		role: "助理教练 / 剪辑",
		joined: "2023年10月",
		work: "偶尔剪辑视频和带训",
		message: "比我会踢球的没我会攀岩，比我会攀岩的没我会踢球",
	},
	{
		name: "牛牛 Angelina",
		photo: "photos/angelina.jpg",
		role: "队员关怀官",
		joined: "2023年10月",
		work: "发射关怀",
		message: "球衣名字是 Geli，但这并不是因为我喜欢吃蛤蜊",
	},
	{
		name: "小黄鸭",
		photo: "photos/duck.jpeg",
		role: "队员关怀官",
		joined: "2023年11月",
		work: "和大家 networking，也会参与设计",
		message: "我的理想型是 Hello Kitty",
	},
	{
		name: "Jennie 宝宝龙",
		photo: "photos/jennie.PNG",
		role: "宣传部长",
		joined: "2025年12月",
		work: "拍照片、剪视频、发视频，每日活着中",
		message: "这是史上最萌的想说什么",
	},
	{
		name: "孟媛 Mona",
		photo: "photos/mona.jpg",
		role: "Rec球队经理",
		joined: "2023年12月",
		work: "组织 Rec Team 训练",
		message: "女人一不踢球就变坏！",
	},
	{
		name: "小球 Tina",
		photo: "photos/tina.JPG",
		role: "Rec球队经理",
		joined: "2024年3月",
		work: "组织 Rec Team 训练",
		message: "所有人都来踢球！",
	},
	{
		name: "Yuchan 肉松大贝",
		photo: "photos/yuchan.jpg",
		role: "秘书长",
		joined: "2023年10月",
		work: "为俱乐部提供行政支持，协调俱乐部内外沟通，组织安排俱乐部各类活动及日程",
		message: "Enjoy the purest football",
	},
	{
		name: "JZ",
		photo: "photos/jz.jpg",
		role: "Rec球队队长",
		joined: "2026年4月",
		work: "招新、组织 Rec 联赛、辅助每周六 Rec 训练",
		message: "西班牙华裔，西班牙语是母语！",
	},
	{
		name: "Lele",
		photo: "photos/Lele.jpg",
		role: "副手财务",
		joined: "2025年7月",
		work: "管账、申请资金",
		message: "最重要的是每场球都不要受伤",
	},
	{
		name: "Jiayi",
		photo: "photos/jiayi.jpg",
		role: "社交部长",
		joined: "2024年5月",
		work: "传销式拉人、组织 social 活动、寻找机会抓大家出去玩",
		message:
			"📢 前排广告 感谢楼主 📢📢📢 Social 部门火热招新🔥 欢迎一起来组织 social 活动，加入即享免费精彩福利，桌游管够，更有机会畅玩英国🚶🏻‍♀️ 心动不如行动，赶快拿起电话抢购吧🫡",
	},
	{
		name: "Yihan",
		photo: "photos/yihan.jpg",
		role: "财务/Dev球队队长",
		joined: "2023年10月",
		work: "时刻私聊没有按时交钱的朋友们，组织 Dev 组联赛、训练、找教练、活跃气氛",
		message: "什么时候联赛才可以拿冠军啊？！我要进球！",
	},
];
